version: '2'
services:
 mongo:
   image: mongo:3.4
   command: --nojournal
   networks:
     - fiware
 orion:
   image: fiware/orion
   links:
     - mongo
   ports:
     - "1026:1026"
   command: -dbhost mongo
   networks:
     - fiware
 spark-master:
   image: bde2020/spark-master:2.4.4-hadoop2.7
   container_name: spark-master
   ports:
     - "8080:8080"
     - "7077:7077"
     - "9001:9001"
   environment:
     - INIT_DAEMON_STEP=setup_spark
     - "constraint:node==spark-master"
   networks:
     - fiware
 spark-worker-1:
   image: bde2020/spark-worker:2.4.4-hadoop2.7
   container_name: spark-worker-1
   depends_on:
    - spark-master
   ports:
     - "8081:8081"
   environment:
     - "SPARK_MASTER=spark://spark-master:7077"
     - "constraint:node==spark-master"
   networks:
     - fiware
networks:
  fiware: